/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SwSPI_Master_1.h"
#include "SwSPI_Master_1_PVT.h"
#include "SwSPI_Master_1_SPI_MISO.h"
#include "SwSPI_Master_1_SPI_MISO_aliases.h"
#include "SwSPI_Master_1_SPI_CS.h"
#include "SwSPI_Master_1_SPI_CS_aliases.h"
#include "SwSPI_Master_1_SPI_MOSI.h"
#include "SwSPI_Master_1_SPI_MOSI_aliases.h"
#include "SwSPI_Master_1_SPI_SCK.h"
#include "SwSPI_Master_1_SPI_SCK_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

