/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "RTC.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "LCD.h"
#include "Timer_LED.h"
#include "Int_Timer_Led.h"
#include "timer_clock.h"
#include "LED_PIN.h"
#include "LED_PIN_aliases.h"
#include "SwSPI_Master.h"
#include "SwSPI_Master_PVT.h"
#include "UART_XB.h"
#include "UART_XB_SPI_UART.h"
#include "UART_XB_PINS.h"
#include "UART_XB_SPI_UART_PVT.h"
#include "UART_XB_PVT.h"
#include "UART_XB_BOOT.h"
#include "AppDelay.h"
#include "SDinsert.h"
#include "SDinsert_aliases.h"
#include "GatePin.h"
#include "GatePin_aliases.h"
#include "GATE_INT.h"
#include "debug_pulse_clock.h"
#include "debug_pulse_clock_aliases.h"
#include "debug.h"
#include "debug_aliases.h"
#include "INT_DEBUG.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "SwSPI_Master_SPIInPort.h"
#include "SwSPI_Master_SPIInPort_aliases.h"
#include "SwSPI_Master_SPIOutPort.h"
#include "SwSPI_Master_SPIOutPort_aliases.h"
#include "UART_XB_SCBCLK.h"
#include "UART_XB_tx.h"
#include "UART_XB_tx_aliases.h"
#include "UART_XB_SCB_IRQ.h"
#include "UART_XB_rx.h"
#include "UART_XB_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

