/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "butt_stop.h"
#include "butt_stop_aliases.h"
#include "Pin_red.h"
#include "Pin_red_aliases.h"
#include "Pin_blue.h"
#include "Pin_blue_aliases.h"
#include "Pin_green.h"
#include "Pin_green_aliases.h"
#include "pin_wire.h"
#include "pin_wire_aliases.h"
#include "isr_wire.h"
#include "Timer_wire.h"
#include "Clock.h"
#include "isr_uart.h"
#include "Clock_1.h"
#include "isr_stop.h"
#include "Timer_uart.h"
#include "isr_wstart.h"
#include "isr_ustart.h"
#include "UART.h"
#include "UART_IntClock.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

