#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include "cydevice_trm.h"

/* isr */
#define isr__INTC_CLR_EN_REG CYREG_CM0_ICER
#define isr__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define isr__INTC_MASK 0x10000u
#define isr__INTC_NUMBER 16u
#define isr__INTC_PRIOR_MASK 0xC0u
#define isr__INTC_PRIOR_NUM 3u
#define isr__INTC_PRIOR_REG CYREG_CM0_IPR4
#define isr__INTC_SET_EN_REG CYREG_CM0_ISER
#define isr__INTC_SET_PD_REG CYREG_CM0_ISPR

/* xbee_rx */
#define xbee_rx__0__DM__MASK 0x7000u
#define xbee_rx__0__DM__SHIFT 12
#define xbee_rx__0__DR CYREG_PRT0_DR
#define xbee_rx__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define xbee_rx__0__HSIOM_MASK 0x000F0000u
#define xbee_rx__0__HSIOM_SHIFT 16u
#define xbee_rx__0__INTCFG CYREG_PRT0_INTCFG
#define xbee_rx__0__INTSTAT CYREG_PRT0_INTSTAT
#define xbee_rx__0__MASK 0x10u
#define xbee_rx__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define xbee_rx__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define xbee_rx__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define xbee_rx__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define xbee_rx__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define xbee_rx__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define xbee_rx__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define xbee_rx__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define xbee_rx__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define xbee_rx__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define xbee_rx__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define xbee_rx__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define xbee_rx__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define xbee_rx__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define xbee_rx__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define xbee_rx__0__PC CYREG_PRT0_PC
#define xbee_rx__0__PC2 CYREG_PRT0_PC2
#define xbee_rx__0__PORT 0u
#define xbee_rx__0__PS CYREG_PRT0_PS
#define xbee_rx__0__SHIFT 4
#define xbee_rx__DR CYREG_PRT0_DR
#define xbee_rx__INTCFG CYREG_PRT0_INTCFG
#define xbee_rx__INTSTAT CYREG_PRT0_INTSTAT
#define xbee_rx__MASK 0x10u
#define xbee_rx__PA__CFG0 CYREG_UDB_PA0_CFG0
#define xbee_rx__PA__CFG1 CYREG_UDB_PA0_CFG1
#define xbee_rx__PA__CFG10 CYREG_UDB_PA0_CFG10
#define xbee_rx__PA__CFG11 CYREG_UDB_PA0_CFG11
#define xbee_rx__PA__CFG12 CYREG_UDB_PA0_CFG12
#define xbee_rx__PA__CFG13 CYREG_UDB_PA0_CFG13
#define xbee_rx__PA__CFG14 CYREG_UDB_PA0_CFG14
#define xbee_rx__PA__CFG2 CYREG_UDB_PA0_CFG2
#define xbee_rx__PA__CFG3 CYREG_UDB_PA0_CFG3
#define xbee_rx__PA__CFG4 CYREG_UDB_PA0_CFG4
#define xbee_rx__PA__CFG5 CYREG_UDB_PA0_CFG5
#define xbee_rx__PA__CFG6 CYREG_UDB_PA0_CFG6
#define xbee_rx__PA__CFG7 CYREG_UDB_PA0_CFG7
#define xbee_rx__PA__CFG8 CYREG_UDB_PA0_CFG8
#define xbee_rx__PA__CFG9 CYREG_UDB_PA0_CFG9
#define xbee_rx__PC CYREG_PRT0_PC
#define xbee_rx__PC2 CYREG_PRT0_PC2
#define xbee_rx__PORT 0u
#define xbee_rx__PS CYREG_PRT0_PS
#define xbee_rx__SHIFT 4

/* xbee_SCB */
#define xbee_SCB__BIST_CONTROL CYREG_SCB1_BIST_CONTROL
#define xbee_SCB__BIST_DATA CYREG_SCB1_BIST_DATA
#define xbee_SCB__CTRL CYREG_SCB1_CTRL
#define xbee_SCB__EZ_DATA00 CYREG_SCB1_EZ_DATA00
#define xbee_SCB__EZ_DATA01 CYREG_SCB1_EZ_DATA01
#define xbee_SCB__EZ_DATA02 CYREG_SCB1_EZ_DATA02
#define xbee_SCB__EZ_DATA03 CYREG_SCB1_EZ_DATA03
#define xbee_SCB__EZ_DATA04 CYREG_SCB1_EZ_DATA04
#define xbee_SCB__EZ_DATA05 CYREG_SCB1_EZ_DATA05
#define xbee_SCB__EZ_DATA06 CYREG_SCB1_EZ_DATA06
#define xbee_SCB__EZ_DATA07 CYREG_SCB1_EZ_DATA07
#define xbee_SCB__EZ_DATA08 CYREG_SCB1_EZ_DATA08
#define xbee_SCB__EZ_DATA09 CYREG_SCB1_EZ_DATA09
#define xbee_SCB__EZ_DATA10 CYREG_SCB1_EZ_DATA10
#define xbee_SCB__EZ_DATA11 CYREG_SCB1_EZ_DATA11
#define xbee_SCB__EZ_DATA12 CYREG_SCB1_EZ_DATA12
#define xbee_SCB__EZ_DATA13 CYREG_SCB1_EZ_DATA13
#define xbee_SCB__EZ_DATA14 CYREG_SCB1_EZ_DATA14
#define xbee_SCB__EZ_DATA15 CYREG_SCB1_EZ_DATA15
#define xbee_SCB__EZ_DATA16 CYREG_SCB1_EZ_DATA16
#define xbee_SCB__EZ_DATA17 CYREG_SCB1_EZ_DATA17
#define xbee_SCB__EZ_DATA18 CYREG_SCB1_EZ_DATA18
#define xbee_SCB__EZ_DATA19 CYREG_SCB1_EZ_DATA19
#define xbee_SCB__EZ_DATA20 CYREG_SCB1_EZ_DATA20
#define xbee_SCB__EZ_DATA21 CYREG_SCB1_EZ_DATA21
#define xbee_SCB__EZ_DATA22 CYREG_SCB1_EZ_DATA22
#define xbee_SCB__EZ_DATA23 CYREG_SCB1_EZ_DATA23
#define xbee_SCB__EZ_DATA24 CYREG_SCB1_EZ_DATA24
#define xbee_SCB__EZ_DATA25 CYREG_SCB1_EZ_DATA25
#define xbee_SCB__EZ_DATA26 CYREG_SCB1_EZ_DATA26
#define xbee_SCB__EZ_DATA27 CYREG_SCB1_EZ_DATA27
#define xbee_SCB__EZ_DATA28 CYREG_SCB1_EZ_DATA28
#define xbee_SCB__EZ_DATA29 CYREG_SCB1_EZ_DATA29
#define xbee_SCB__EZ_DATA30 CYREG_SCB1_EZ_DATA30
#define xbee_SCB__EZ_DATA31 CYREG_SCB1_EZ_DATA31
#define xbee_SCB__I2C_CFG CYREG_SCB1_I2C_CFG
#define xbee_SCB__I2C_CTRL CYREG_SCB1_I2C_CTRL
#define xbee_SCB__I2C_M_CMD CYREG_SCB1_I2C_M_CMD
#define xbee_SCB__I2C_S_CMD CYREG_SCB1_I2C_S_CMD
#define xbee_SCB__I2C_STATUS CYREG_SCB1_I2C_STATUS
#define xbee_SCB__INTR_CAUSE CYREG_SCB1_INTR_CAUSE
#define xbee_SCB__INTR_I2C_EC CYREG_SCB1_INTR_I2C_EC
#define xbee_SCB__INTR_I2C_EC_MASK CYREG_SCB1_INTR_I2C_EC_MASK
#define xbee_SCB__INTR_I2C_EC_MASKED CYREG_SCB1_INTR_I2C_EC_MASKED
#define xbee_SCB__INTR_M CYREG_SCB1_INTR_M
#define xbee_SCB__INTR_M_MASK CYREG_SCB1_INTR_M_MASK
#define xbee_SCB__INTR_M_MASKED CYREG_SCB1_INTR_M_MASKED
#define xbee_SCB__INTR_M_SET CYREG_SCB1_INTR_M_SET
#define xbee_SCB__INTR_RX CYREG_SCB1_INTR_RX
#define xbee_SCB__INTR_RX_MASK CYREG_SCB1_INTR_RX_MASK
#define xbee_SCB__INTR_RX_MASKED CYREG_SCB1_INTR_RX_MASKED
#define xbee_SCB__INTR_RX_SET CYREG_SCB1_INTR_RX_SET
#define xbee_SCB__INTR_S CYREG_SCB1_INTR_S
#define xbee_SCB__INTR_S_MASK CYREG_SCB1_INTR_S_MASK
#define xbee_SCB__INTR_S_MASKED CYREG_SCB1_INTR_S_MASKED
#define xbee_SCB__INTR_S_SET CYREG_SCB1_INTR_S_SET
#define xbee_SCB__INTR_SPI_EC CYREG_SCB1_INTR_SPI_EC
#define xbee_SCB__INTR_SPI_EC_MASK CYREG_SCB1_INTR_SPI_EC_MASK
#define xbee_SCB__INTR_SPI_EC_MASKED CYREG_SCB1_INTR_SPI_EC_MASKED
#define xbee_SCB__INTR_TX CYREG_SCB1_INTR_TX
#define xbee_SCB__INTR_TX_MASK CYREG_SCB1_INTR_TX_MASK
#define xbee_SCB__INTR_TX_MASKED CYREG_SCB1_INTR_TX_MASKED
#define xbee_SCB__INTR_TX_SET CYREG_SCB1_INTR_TX_SET
#define xbee_SCB__RX_CTRL CYREG_SCB1_RX_CTRL
#define xbee_SCB__RX_FIFO_CTRL CYREG_SCB1_RX_FIFO_CTRL
#define xbee_SCB__RX_FIFO_RD CYREG_SCB1_RX_FIFO_RD
#define xbee_SCB__RX_FIFO_RD_SILENT CYREG_SCB1_RX_FIFO_RD_SILENT
#define xbee_SCB__RX_FIFO_STATUS CYREG_SCB1_RX_FIFO_STATUS
#define xbee_SCB__RX_MATCH CYREG_SCB1_RX_MATCH
#define xbee_SCB__SPI_CTRL CYREG_SCB1_SPI_CTRL
#define xbee_SCB__SPI_STATUS CYREG_SCB1_SPI_STATUS
#define xbee_SCB__SS0_POSISTION 0u
#define xbee_SCB__SS1_POSISTION 1u
#define xbee_SCB__SS2_POSISTION 2u
#define xbee_SCB__SS3_POSISTION 3u
#define xbee_SCB__STATUS CYREG_SCB1_STATUS
#define xbee_SCB__TX_CTRL CYREG_SCB1_TX_CTRL
#define xbee_SCB__TX_FIFO_CTRL CYREG_SCB1_TX_FIFO_CTRL
#define xbee_SCB__TX_FIFO_STATUS CYREG_SCB1_TX_FIFO_STATUS
#define xbee_SCB__TX_FIFO_WR CYREG_SCB1_TX_FIFO_WR
#define xbee_SCB__UART_CTRL CYREG_SCB1_UART_CTRL
#define xbee_SCB__UART_RX_CTRL CYREG_SCB1_UART_RX_CTRL
#define xbee_SCB__UART_RX_STATUS CYREG_SCB1_UART_RX_STATUS
#define xbee_SCB__UART_TX_CTRL CYREG_SCB1_UART_TX_CTRL

/* xbee_SCBCLK */
#define xbee_SCBCLK__DIVIDER_MASK 0x0000FFFFu
#define xbee_SCBCLK__ENABLE CYREG_CLK_DIVIDER_A00
#define xbee_SCBCLK__ENABLE_MASK 0x80000000u
#define xbee_SCBCLK__MASK 0x80000000u
#define xbee_SCBCLK__REGISTER CYREG_CLK_DIVIDER_A00

/* xbee_tx */
#define xbee_tx__0__DM__MASK 0x38000u
#define xbee_tx__0__DM__SHIFT 15
#define xbee_tx__0__DR CYREG_PRT0_DR
#define xbee_tx__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define xbee_tx__0__HSIOM_MASK 0x00F00000u
#define xbee_tx__0__HSIOM_SHIFT 20u
#define xbee_tx__0__INTCFG CYREG_PRT0_INTCFG
#define xbee_tx__0__INTSTAT CYREG_PRT0_INTSTAT
#define xbee_tx__0__MASK 0x20u
#define xbee_tx__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define xbee_tx__0__OUT_SEL_SHIFT 10u
#define xbee_tx__0__OUT_SEL_VAL -1u
#define xbee_tx__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define xbee_tx__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define xbee_tx__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define xbee_tx__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define xbee_tx__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define xbee_tx__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define xbee_tx__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define xbee_tx__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define xbee_tx__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define xbee_tx__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define xbee_tx__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define xbee_tx__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define xbee_tx__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define xbee_tx__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define xbee_tx__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define xbee_tx__0__PC CYREG_PRT0_PC
#define xbee_tx__0__PC2 CYREG_PRT0_PC2
#define xbee_tx__0__PORT 0u
#define xbee_tx__0__PS CYREG_PRT0_PS
#define xbee_tx__0__SHIFT 5
#define xbee_tx__DR CYREG_PRT0_DR
#define xbee_tx__INTCFG CYREG_PRT0_INTCFG
#define xbee_tx__INTSTAT CYREG_PRT0_INTSTAT
#define xbee_tx__MASK 0x20u
#define xbee_tx__PA__CFG0 CYREG_UDB_PA0_CFG0
#define xbee_tx__PA__CFG1 CYREG_UDB_PA0_CFG1
#define xbee_tx__PA__CFG10 CYREG_UDB_PA0_CFG10
#define xbee_tx__PA__CFG11 CYREG_UDB_PA0_CFG11
#define xbee_tx__PA__CFG12 CYREG_UDB_PA0_CFG12
#define xbee_tx__PA__CFG13 CYREG_UDB_PA0_CFG13
#define xbee_tx__PA__CFG14 CYREG_UDB_PA0_CFG14
#define xbee_tx__PA__CFG2 CYREG_UDB_PA0_CFG2
#define xbee_tx__PA__CFG3 CYREG_UDB_PA0_CFG3
#define xbee_tx__PA__CFG4 CYREG_UDB_PA0_CFG4
#define xbee_tx__PA__CFG5 CYREG_UDB_PA0_CFG5
#define xbee_tx__PA__CFG6 CYREG_UDB_PA0_CFG6
#define xbee_tx__PA__CFG7 CYREG_UDB_PA0_CFG7
#define xbee_tx__PA__CFG8 CYREG_UDB_PA0_CFG8
#define xbee_tx__PA__CFG9 CYREG_UDB_PA0_CFG9
#define xbee_tx__PC CYREG_PRT0_PC
#define xbee_tx__PC2 CYREG_PRT0_PC2
#define xbee_tx__PORT 0u
#define xbee_tx__PS CYREG_PRT0_PS
#define xbee_tx__SHIFT 5

/* Clock */
#define Clock__DIVIDER_MASK 0x0000FFFFu
#define Clock__ENABLE CYREG_CLK_DIVIDER_B00
#define Clock__ENABLE_MASK 0x80000000u
#define Clock__MASK 0x80000000u
#define Clock__REGISTER CYREG_CLK_DIVIDER_B00

/* start */
#define start__0__DM__MASK 0xE00000u
#define start__0__DM__SHIFT 21
#define start__0__DR CYREG_PRT0_DR
#define start__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define start__0__HSIOM_MASK 0xF0000000u
#define start__0__HSIOM_SHIFT 28u
#define start__0__INTCFG CYREG_PRT0_INTCFG
#define start__0__INTSTAT CYREG_PRT0_INTSTAT
#define start__0__MASK 0x80u
#define start__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define start__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define start__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define start__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define start__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define start__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define start__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define start__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define start__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define start__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define start__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define start__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define start__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define start__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define start__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define start__0__PC CYREG_PRT0_PC
#define start__0__PC2 CYREG_PRT0_PC2
#define start__0__PORT 0u
#define start__0__PS CYREG_PRT0_PS
#define start__0__SHIFT 7
#define start__DR CYREG_PRT0_DR
#define start__INTCFG CYREG_PRT0_INTCFG
#define start__INTSTAT CYREG_PRT0_INTSTAT
#define start__MASK 0x80u
#define start__PA__CFG0 CYREG_UDB_PA0_CFG0
#define start__PA__CFG1 CYREG_UDB_PA0_CFG1
#define start__PA__CFG10 CYREG_UDB_PA0_CFG10
#define start__PA__CFG11 CYREG_UDB_PA0_CFG11
#define start__PA__CFG12 CYREG_UDB_PA0_CFG12
#define start__PA__CFG13 CYREG_UDB_PA0_CFG13
#define start__PA__CFG14 CYREG_UDB_PA0_CFG14
#define start__PA__CFG2 CYREG_UDB_PA0_CFG2
#define start__PA__CFG3 CYREG_UDB_PA0_CFG3
#define start__PA__CFG4 CYREG_UDB_PA0_CFG4
#define start__PA__CFG5 CYREG_UDB_PA0_CFG5
#define start__PA__CFG6 CYREG_UDB_PA0_CFG6
#define start__PA__CFG7 CYREG_UDB_PA0_CFG7
#define start__PA__CFG8 CYREG_UDB_PA0_CFG8
#define start__PA__CFG9 CYREG_UDB_PA0_CFG9
#define start__PC CYREG_PRT0_PC
#define start__PC2 CYREG_PRT0_PC2
#define start__PORT 0u
#define start__PS CYREG_PRT0_PS
#define start__SHIFT 7
#define start__SNAP CYREG_PRT0_INTSTAT

/* timer_cy_m0s8_tcpwm_1 */
#define timer_cy_m0s8_tcpwm_1__CC CYREG_TCPWM_CNT0_CC
#define timer_cy_m0s8_tcpwm_1__CC_BUFF CYREG_TCPWM_CNT0_CC_BUFF
#define timer_cy_m0s8_tcpwm_1__COUNTER CYREG_TCPWM_CNT0_COUNTER
#define timer_cy_m0s8_tcpwm_1__CTRL CYREG_TCPWM_CNT0_CTRL
#define timer_cy_m0s8_tcpwm_1__INTR CYREG_TCPWM_CNT0_INTR
#define timer_cy_m0s8_tcpwm_1__INTR_MASK CYREG_TCPWM_CNT0_INTR_MASK
#define timer_cy_m0s8_tcpwm_1__INTR_MASKED CYREG_TCPWM_CNT0_INTR_MASKED
#define timer_cy_m0s8_tcpwm_1__INTR_SET CYREG_TCPWM_CNT0_INTR_SET
#define timer_cy_m0s8_tcpwm_1__PERIOD CYREG_TCPWM_CNT0_PERIOD
#define timer_cy_m0s8_tcpwm_1__PERIOD_BUFF CYREG_TCPWM_CNT0_PERIOD_BUFF
#define timer_cy_m0s8_tcpwm_1__STATUS CYREG_TCPWM_CNT0_STATUS
#define timer_cy_m0s8_tcpwm_1__TCPWM_CMD CYREG_TCPWM_CMD
#define timer_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_MASK 0x01u
#define timer_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_SHIFT 0
#define timer_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_MASK 0x100u
#define timer_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_SHIFT 8
#define timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_MASK 0x1000000u
#define timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_SHIFT 24
#define timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_MASK 0x10000u
#define timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_SHIFT 16
#define timer_cy_m0s8_tcpwm_1__TCPWM_CTRL CYREG_TCPWM_CTRL
#define timer_cy_m0s8_tcpwm_1__TCPWM_CTRL_MASK 0x01u
#define timer_cy_m0s8_tcpwm_1__TCPWM_CTRL_SHIFT 0
#define timer_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE CYREG_TCPWM_INTR_CAUSE
#define timer_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_MASK 0x01u
#define timer_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_SHIFT 0
#define timer_cy_m0s8_tcpwm_1__TCPWM_NUMBER 0u
#define timer_cy_m0s8_tcpwm_1__TR_CTRL0 CYREG_TCPWM_CNT0_TR_CTRL0
#define timer_cy_m0s8_tcpwm_1__TR_CTRL1 CYREG_TCPWM_CNT0_TR_CTRL1
#define timer_cy_m0s8_tcpwm_1__TR_CTRL2 CYREG_TCPWM_CNT0_TR_CTRL2

/* wired */
#define wired__0__DM__MASK 0xE00000u
#define wired__0__DM__SHIFT 21
#define wired__0__DR CYREG_PRT2_DR
#define wired__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define wired__0__HSIOM_MASK 0xF0000000u
#define wired__0__HSIOM_SHIFT 28u
#define wired__0__INTCFG CYREG_PRT2_INTCFG
#define wired__0__INTSTAT CYREG_PRT2_INTSTAT
#define wired__0__MASK 0x80u
#define wired__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define wired__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define wired__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define wired__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define wired__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define wired__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define wired__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define wired__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define wired__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define wired__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define wired__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define wired__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define wired__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define wired__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define wired__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define wired__0__PC CYREG_PRT2_PC
#define wired__0__PC2 CYREG_PRT2_PC2
#define wired__0__PORT 2u
#define wired__0__PS CYREG_PRT2_PS
#define wired__0__SHIFT 7
#define wired__DR CYREG_PRT2_DR
#define wired__INTCFG CYREG_PRT2_INTCFG
#define wired__INTSTAT CYREG_PRT2_INTSTAT
#define wired__MASK 0x80u
#define wired__PA__CFG0 CYREG_UDB_PA2_CFG0
#define wired__PA__CFG1 CYREG_UDB_PA2_CFG1
#define wired__PA__CFG10 CYREG_UDB_PA2_CFG10
#define wired__PA__CFG11 CYREG_UDB_PA2_CFG11
#define wired__PA__CFG12 CYREG_UDB_PA2_CFG12
#define wired__PA__CFG13 CYREG_UDB_PA2_CFG13
#define wired__PA__CFG14 CYREG_UDB_PA2_CFG14
#define wired__PA__CFG2 CYREG_UDB_PA2_CFG2
#define wired__PA__CFG3 CYREG_UDB_PA2_CFG3
#define wired__PA__CFG4 CYREG_UDB_PA2_CFG4
#define wired__PA__CFG5 CYREG_UDB_PA2_CFG5
#define wired__PA__CFG6 CYREG_UDB_PA2_CFG6
#define wired__PA__CFG7 CYREG_UDB_PA2_CFG7
#define wired__PA__CFG8 CYREG_UDB_PA2_CFG8
#define wired__PA__CFG9 CYREG_UDB_PA2_CFG9
#define wired__PC CYREG_PRT2_PC
#define wired__PC2 CYREG_PRT2_PC2
#define wired__PORT 2u
#define wired__PS CYREG_PRT2_PS
#define wired__SHIFT 7

/* cancel */
#define cancel__0__DM__MASK 0xE00000u
#define cancel__0__DM__SHIFT 21
#define cancel__0__DR CYREG_PRT3_DR
#define cancel__0__HSIOM CYREG_HSIOM_PORT_SEL3
#define cancel__0__HSIOM_MASK 0xF0000000u
#define cancel__0__HSIOM_SHIFT 28u
#define cancel__0__INTCFG CYREG_PRT3_INTCFG
#define cancel__0__INTSTAT CYREG_PRT3_INTSTAT
#define cancel__0__MASK 0x80u
#define cancel__0__PA__CFG0 CYREG_UDB_PA3_CFG0
#define cancel__0__PA__CFG1 CYREG_UDB_PA3_CFG1
#define cancel__0__PA__CFG10 CYREG_UDB_PA3_CFG10
#define cancel__0__PA__CFG11 CYREG_UDB_PA3_CFG11
#define cancel__0__PA__CFG12 CYREG_UDB_PA3_CFG12
#define cancel__0__PA__CFG13 CYREG_UDB_PA3_CFG13
#define cancel__0__PA__CFG14 CYREG_UDB_PA3_CFG14
#define cancel__0__PA__CFG2 CYREG_UDB_PA3_CFG2
#define cancel__0__PA__CFG3 CYREG_UDB_PA3_CFG3
#define cancel__0__PA__CFG4 CYREG_UDB_PA3_CFG4
#define cancel__0__PA__CFG5 CYREG_UDB_PA3_CFG5
#define cancel__0__PA__CFG6 CYREG_UDB_PA3_CFG6
#define cancel__0__PA__CFG7 CYREG_UDB_PA3_CFG7
#define cancel__0__PA__CFG8 CYREG_UDB_PA3_CFG8
#define cancel__0__PA__CFG9 CYREG_UDB_PA3_CFG9
#define cancel__0__PC CYREG_PRT3_PC
#define cancel__0__PC2 CYREG_PRT3_PC2
#define cancel__0__PORT 3u
#define cancel__0__PS CYREG_PRT3_PS
#define cancel__0__SHIFT 7
#define cancel__DR CYREG_PRT3_DR
#define cancel__INTCFG CYREG_PRT3_INTCFG
#define cancel__INTSTAT CYREG_PRT3_INTSTAT
#define cancel__MASK 0x80u
#define cancel__PA__CFG0 CYREG_UDB_PA3_CFG0
#define cancel__PA__CFG1 CYREG_UDB_PA3_CFG1
#define cancel__PA__CFG10 CYREG_UDB_PA3_CFG10
#define cancel__PA__CFG11 CYREG_UDB_PA3_CFG11
#define cancel__PA__CFG12 CYREG_UDB_PA3_CFG12
#define cancel__PA__CFG13 CYREG_UDB_PA3_CFG13
#define cancel__PA__CFG14 CYREG_UDB_PA3_CFG14
#define cancel__PA__CFG2 CYREG_UDB_PA3_CFG2
#define cancel__PA__CFG3 CYREG_UDB_PA3_CFG3
#define cancel__PA__CFG4 CYREG_UDB_PA3_CFG4
#define cancel__PA__CFG5 CYREG_UDB_PA3_CFG5
#define cancel__PA__CFG6 CYREG_UDB_PA3_CFG6
#define cancel__PA__CFG7 CYREG_UDB_PA3_CFG7
#define cancel__PA__CFG8 CYREG_UDB_PA3_CFG8
#define cancel__PA__CFG9 CYREG_UDB_PA3_CFG9
#define cancel__PC CYREG_PRT3_PC
#define cancel__PC2 CYREG_PRT3_PC2
#define cancel__PORT 3u
#define cancel__PS CYREG_PRT3_PS
#define cancel__SHIFT 7
#define cancel__SNAP CYREG_PRT3_INTSTAT

/* display_LCDPort */
#define display_LCDPort__0__DM__MASK 0x07u
#define display_LCDPort__0__DM__SHIFT 0
#define display_LCDPort__0__DR CYREG_PRT2_DR
#define display_LCDPort__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define display_LCDPort__0__HSIOM_MASK 0x0000000Fu
#define display_LCDPort__0__HSIOM_SHIFT 0u
#define display_LCDPort__0__INTCFG CYREG_PRT2_INTCFG
#define display_LCDPort__0__INTSTAT CYREG_PRT2_INTSTAT
#define display_LCDPort__0__MASK 0x01u
#define display_LCDPort__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define display_LCDPort__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define display_LCDPort__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define display_LCDPort__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define display_LCDPort__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define display_LCDPort__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define display_LCDPort__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define display_LCDPort__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define display_LCDPort__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define display_LCDPort__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define display_LCDPort__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define display_LCDPort__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define display_LCDPort__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define display_LCDPort__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define display_LCDPort__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define display_LCDPort__0__PC CYREG_PRT2_PC
#define display_LCDPort__0__PC2 CYREG_PRT2_PC2
#define display_LCDPort__0__PORT 2u
#define display_LCDPort__0__PS CYREG_PRT2_PS
#define display_LCDPort__0__SHIFT 0
#define display_LCDPort__1__DM__MASK 0x38u
#define display_LCDPort__1__DM__SHIFT 3
#define display_LCDPort__1__DR CYREG_PRT2_DR
#define display_LCDPort__1__HSIOM CYREG_HSIOM_PORT_SEL2
#define display_LCDPort__1__HSIOM_MASK 0x000000F0u
#define display_LCDPort__1__HSIOM_SHIFT 4u
#define display_LCDPort__1__INTCFG CYREG_PRT2_INTCFG
#define display_LCDPort__1__INTSTAT CYREG_PRT2_INTSTAT
#define display_LCDPort__1__MASK 0x02u
#define display_LCDPort__1__PA__CFG0 CYREG_UDB_PA2_CFG0
#define display_LCDPort__1__PA__CFG1 CYREG_UDB_PA2_CFG1
#define display_LCDPort__1__PA__CFG10 CYREG_UDB_PA2_CFG10
#define display_LCDPort__1__PA__CFG11 CYREG_UDB_PA2_CFG11
#define display_LCDPort__1__PA__CFG12 CYREG_UDB_PA2_CFG12
#define display_LCDPort__1__PA__CFG13 CYREG_UDB_PA2_CFG13
#define display_LCDPort__1__PA__CFG14 CYREG_UDB_PA2_CFG14
#define display_LCDPort__1__PA__CFG2 CYREG_UDB_PA2_CFG2
#define display_LCDPort__1__PA__CFG3 CYREG_UDB_PA2_CFG3
#define display_LCDPort__1__PA__CFG4 CYREG_UDB_PA2_CFG4
#define display_LCDPort__1__PA__CFG5 CYREG_UDB_PA2_CFG5
#define display_LCDPort__1__PA__CFG6 CYREG_UDB_PA2_CFG6
#define display_LCDPort__1__PA__CFG7 CYREG_UDB_PA2_CFG7
#define display_LCDPort__1__PA__CFG8 CYREG_UDB_PA2_CFG8
#define display_LCDPort__1__PA__CFG9 CYREG_UDB_PA2_CFG9
#define display_LCDPort__1__PC CYREG_PRT2_PC
#define display_LCDPort__1__PC2 CYREG_PRT2_PC2
#define display_LCDPort__1__PORT 2u
#define display_LCDPort__1__PS CYREG_PRT2_PS
#define display_LCDPort__1__SHIFT 1
#define display_LCDPort__2__DM__MASK 0x1C0u
#define display_LCDPort__2__DM__SHIFT 6
#define display_LCDPort__2__DR CYREG_PRT2_DR
#define display_LCDPort__2__HSIOM CYREG_HSIOM_PORT_SEL2
#define display_LCDPort__2__HSIOM_MASK 0x00000F00u
#define display_LCDPort__2__HSIOM_SHIFT 8u
#define display_LCDPort__2__INTCFG CYREG_PRT2_INTCFG
#define display_LCDPort__2__INTSTAT CYREG_PRT2_INTSTAT
#define display_LCDPort__2__MASK 0x04u
#define display_LCDPort__2__PA__CFG0 CYREG_UDB_PA2_CFG0
#define display_LCDPort__2__PA__CFG1 CYREG_UDB_PA2_CFG1
#define display_LCDPort__2__PA__CFG10 CYREG_UDB_PA2_CFG10
#define display_LCDPort__2__PA__CFG11 CYREG_UDB_PA2_CFG11
#define display_LCDPort__2__PA__CFG12 CYREG_UDB_PA2_CFG12
#define display_LCDPort__2__PA__CFG13 CYREG_UDB_PA2_CFG13
#define display_LCDPort__2__PA__CFG14 CYREG_UDB_PA2_CFG14
#define display_LCDPort__2__PA__CFG2 CYREG_UDB_PA2_CFG2
#define display_LCDPort__2__PA__CFG3 CYREG_UDB_PA2_CFG3
#define display_LCDPort__2__PA__CFG4 CYREG_UDB_PA2_CFG4
#define display_LCDPort__2__PA__CFG5 CYREG_UDB_PA2_CFG5
#define display_LCDPort__2__PA__CFG6 CYREG_UDB_PA2_CFG6
#define display_LCDPort__2__PA__CFG7 CYREG_UDB_PA2_CFG7
#define display_LCDPort__2__PA__CFG8 CYREG_UDB_PA2_CFG8
#define display_LCDPort__2__PA__CFG9 CYREG_UDB_PA2_CFG9
#define display_LCDPort__2__PC CYREG_PRT2_PC
#define display_LCDPort__2__PC2 CYREG_PRT2_PC2
#define display_LCDPort__2__PORT 2u
#define display_LCDPort__2__PS CYREG_PRT2_PS
#define display_LCDPort__2__SHIFT 2
#define display_LCDPort__3__DM__MASK 0xE00u
#define display_LCDPort__3__DM__SHIFT 9
#define display_LCDPort__3__DR CYREG_PRT2_DR
#define display_LCDPort__3__HSIOM CYREG_HSIOM_PORT_SEL2
#define display_LCDPort__3__HSIOM_MASK 0x0000F000u
#define display_LCDPort__3__HSIOM_SHIFT 12u
#define display_LCDPort__3__INTCFG CYREG_PRT2_INTCFG
#define display_LCDPort__3__INTSTAT CYREG_PRT2_INTSTAT
#define display_LCDPort__3__MASK 0x08u
#define display_LCDPort__3__PA__CFG0 CYREG_UDB_PA2_CFG0
#define display_LCDPort__3__PA__CFG1 CYREG_UDB_PA2_CFG1
#define display_LCDPort__3__PA__CFG10 CYREG_UDB_PA2_CFG10
#define display_LCDPort__3__PA__CFG11 CYREG_UDB_PA2_CFG11
#define display_LCDPort__3__PA__CFG12 CYREG_UDB_PA2_CFG12
#define display_LCDPort__3__PA__CFG13 CYREG_UDB_PA2_CFG13
#define display_LCDPort__3__PA__CFG14 CYREG_UDB_PA2_CFG14
#define display_LCDPort__3__PA__CFG2 CYREG_UDB_PA2_CFG2
#define display_LCDPort__3__PA__CFG3 CYREG_UDB_PA2_CFG3
#define display_LCDPort__3__PA__CFG4 CYREG_UDB_PA2_CFG4
#define display_LCDPort__3__PA__CFG5 CYREG_UDB_PA2_CFG5
#define display_LCDPort__3__PA__CFG6 CYREG_UDB_PA2_CFG6
#define display_LCDPort__3__PA__CFG7 CYREG_UDB_PA2_CFG7
#define display_LCDPort__3__PA__CFG8 CYREG_UDB_PA2_CFG8
#define display_LCDPort__3__PA__CFG9 CYREG_UDB_PA2_CFG9
#define display_LCDPort__3__PC CYREG_PRT2_PC
#define display_LCDPort__3__PC2 CYREG_PRT2_PC2
#define display_LCDPort__3__PORT 2u
#define display_LCDPort__3__PS CYREG_PRT2_PS
#define display_LCDPort__3__SHIFT 3
#define display_LCDPort__4__DM__MASK 0x7000u
#define display_LCDPort__4__DM__SHIFT 12
#define display_LCDPort__4__DR CYREG_PRT2_DR
#define display_LCDPort__4__HSIOM CYREG_HSIOM_PORT_SEL2
#define display_LCDPort__4__HSIOM_MASK 0x000F0000u
#define display_LCDPort__4__HSIOM_SHIFT 16u
#define display_LCDPort__4__INTCFG CYREG_PRT2_INTCFG
#define display_LCDPort__4__INTSTAT CYREG_PRT2_INTSTAT
#define display_LCDPort__4__MASK 0x10u
#define display_LCDPort__4__PA__CFG0 CYREG_UDB_PA2_CFG0
#define display_LCDPort__4__PA__CFG1 CYREG_UDB_PA2_CFG1
#define display_LCDPort__4__PA__CFG10 CYREG_UDB_PA2_CFG10
#define display_LCDPort__4__PA__CFG11 CYREG_UDB_PA2_CFG11
#define display_LCDPort__4__PA__CFG12 CYREG_UDB_PA2_CFG12
#define display_LCDPort__4__PA__CFG13 CYREG_UDB_PA2_CFG13
#define display_LCDPort__4__PA__CFG14 CYREG_UDB_PA2_CFG14
#define display_LCDPort__4__PA__CFG2 CYREG_UDB_PA2_CFG2
#define display_LCDPort__4__PA__CFG3 CYREG_UDB_PA2_CFG3
#define display_LCDPort__4__PA__CFG4 CYREG_UDB_PA2_CFG4
#define display_LCDPort__4__PA__CFG5 CYREG_UDB_PA2_CFG5
#define display_LCDPort__4__PA__CFG6 CYREG_UDB_PA2_CFG6
#define display_LCDPort__4__PA__CFG7 CYREG_UDB_PA2_CFG7
#define display_LCDPort__4__PA__CFG8 CYREG_UDB_PA2_CFG8
#define display_LCDPort__4__PA__CFG9 CYREG_UDB_PA2_CFG9
#define display_LCDPort__4__PC CYREG_PRT2_PC
#define display_LCDPort__4__PC2 CYREG_PRT2_PC2
#define display_LCDPort__4__PORT 2u
#define display_LCDPort__4__PS CYREG_PRT2_PS
#define display_LCDPort__4__SHIFT 4
#define display_LCDPort__5__DM__MASK 0x38000u
#define display_LCDPort__5__DM__SHIFT 15
#define display_LCDPort__5__DR CYREG_PRT2_DR
#define display_LCDPort__5__HSIOM CYREG_HSIOM_PORT_SEL2
#define display_LCDPort__5__HSIOM_MASK 0x00F00000u
#define display_LCDPort__5__HSIOM_SHIFT 20u
#define display_LCDPort__5__INTCFG CYREG_PRT2_INTCFG
#define display_LCDPort__5__INTSTAT CYREG_PRT2_INTSTAT
#define display_LCDPort__5__MASK 0x20u
#define display_LCDPort__5__PA__CFG0 CYREG_UDB_PA2_CFG0
#define display_LCDPort__5__PA__CFG1 CYREG_UDB_PA2_CFG1
#define display_LCDPort__5__PA__CFG10 CYREG_UDB_PA2_CFG10
#define display_LCDPort__5__PA__CFG11 CYREG_UDB_PA2_CFG11
#define display_LCDPort__5__PA__CFG12 CYREG_UDB_PA2_CFG12
#define display_LCDPort__5__PA__CFG13 CYREG_UDB_PA2_CFG13
#define display_LCDPort__5__PA__CFG14 CYREG_UDB_PA2_CFG14
#define display_LCDPort__5__PA__CFG2 CYREG_UDB_PA2_CFG2
#define display_LCDPort__5__PA__CFG3 CYREG_UDB_PA2_CFG3
#define display_LCDPort__5__PA__CFG4 CYREG_UDB_PA2_CFG4
#define display_LCDPort__5__PA__CFG5 CYREG_UDB_PA2_CFG5
#define display_LCDPort__5__PA__CFG6 CYREG_UDB_PA2_CFG6
#define display_LCDPort__5__PA__CFG7 CYREG_UDB_PA2_CFG7
#define display_LCDPort__5__PA__CFG8 CYREG_UDB_PA2_CFG8
#define display_LCDPort__5__PA__CFG9 CYREG_UDB_PA2_CFG9
#define display_LCDPort__5__PC CYREG_PRT2_PC
#define display_LCDPort__5__PC2 CYREG_PRT2_PC2
#define display_LCDPort__5__PORT 2u
#define display_LCDPort__5__PS CYREG_PRT2_PS
#define display_LCDPort__5__SHIFT 5
#define display_LCDPort__6__DM__MASK 0x1C0000u
#define display_LCDPort__6__DM__SHIFT 18
#define display_LCDPort__6__DR CYREG_PRT2_DR
#define display_LCDPort__6__HSIOM CYREG_HSIOM_PORT_SEL2
#define display_LCDPort__6__HSIOM_MASK 0x0F000000u
#define display_LCDPort__6__HSIOM_SHIFT 24u
#define display_LCDPort__6__INTCFG CYREG_PRT2_INTCFG
#define display_LCDPort__6__INTSTAT CYREG_PRT2_INTSTAT
#define display_LCDPort__6__MASK 0x40u
#define display_LCDPort__6__PA__CFG0 CYREG_UDB_PA2_CFG0
#define display_LCDPort__6__PA__CFG1 CYREG_UDB_PA2_CFG1
#define display_LCDPort__6__PA__CFG10 CYREG_UDB_PA2_CFG10
#define display_LCDPort__6__PA__CFG11 CYREG_UDB_PA2_CFG11
#define display_LCDPort__6__PA__CFG12 CYREG_UDB_PA2_CFG12
#define display_LCDPort__6__PA__CFG13 CYREG_UDB_PA2_CFG13
#define display_LCDPort__6__PA__CFG14 CYREG_UDB_PA2_CFG14
#define display_LCDPort__6__PA__CFG2 CYREG_UDB_PA2_CFG2
#define display_LCDPort__6__PA__CFG3 CYREG_UDB_PA2_CFG3
#define display_LCDPort__6__PA__CFG4 CYREG_UDB_PA2_CFG4
#define display_LCDPort__6__PA__CFG5 CYREG_UDB_PA2_CFG5
#define display_LCDPort__6__PA__CFG6 CYREG_UDB_PA2_CFG6
#define display_LCDPort__6__PA__CFG7 CYREG_UDB_PA2_CFG7
#define display_LCDPort__6__PA__CFG8 CYREG_UDB_PA2_CFG8
#define display_LCDPort__6__PA__CFG9 CYREG_UDB_PA2_CFG9
#define display_LCDPort__6__PC CYREG_PRT2_PC
#define display_LCDPort__6__PC2 CYREG_PRT2_PC2
#define display_LCDPort__6__PORT 2u
#define display_LCDPort__6__PS CYREG_PRT2_PS
#define display_LCDPort__6__SHIFT 6
#define display_LCDPort__DR CYREG_PRT2_DR
#define display_LCDPort__INTCFG CYREG_PRT2_INTCFG
#define display_LCDPort__INTSTAT CYREG_PRT2_INTSTAT
#define display_LCDPort__MASK 0x7Fu
#define display_LCDPort__PA__CFG0 CYREG_UDB_PA2_CFG0
#define display_LCDPort__PA__CFG1 CYREG_UDB_PA2_CFG1
#define display_LCDPort__PA__CFG10 CYREG_UDB_PA2_CFG10
#define display_LCDPort__PA__CFG11 CYREG_UDB_PA2_CFG11
#define display_LCDPort__PA__CFG12 CYREG_UDB_PA2_CFG12
#define display_LCDPort__PA__CFG13 CYREG_UDB_PA2_CFG13
#define display_LCDPort__PA__CFG14 CYREG_UDB_PA2_CFG14
#define display_LCDPort__PA__CFG2 CYREG_UDB_PA2_CFG2
#define display_LCDPort__PA__CFG3 CYREG_UDB_PA2_CFG3
#define display_LCDPort__PA__CFG4 CYREG_UDB_PA2_CFG4
#define display_LCDPort__PA__CFG5 CYREG_UDB_PA2_CFG5
#define display_LCDPort__PA__CFG6 CYREG_UDB_PA2_CFG6
#define display_LCDPort__PA__CFG7 CYREG_UDB_PA2_CFG7
#define display_LCDPort__PA__CFG8 CYREG_UDB_PA2_CFG8
#define display_LCDPort__PA__CFG9 CYREG_UDB_PA2_CFG9
#define display_LCDPort__PC CYREG_PRT2_PC
#define display_LCDPort__PC2 CYREG_PRT2_PC2
#define display_LCDPort__PORT 2u
#define display_LCDPort__PS CYREG_PRT2_PS
#define display_LCDPort__SHIFT 0

/* led_red */
#define led_red__0__DM__MASK 0x1C0000u
#define led_red__0__DM__SHIFT 18
#define led_red__0__DR CYREG_PRT1_DR
#define led_red__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define led_red__0__HSIOM_MASK 0x0F000000u
#define led_red__0__HSIOM_SHIFT 24u
#define led_red__0__INTCFG CYREG_PRT1_INTCFG
#define led_red__0__INTSTAT CYREG_PRT1_INTSTAT
#define led_red__0__MASK 0x40u
#define led_red__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define led_red__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define led_red__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define led_red__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define led_red__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define led_red__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define led_red__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define led_red__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define led_red__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define led_red__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define led_red__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define led_red__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define led_red__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define led_red__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define led_red__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define led_red__0__PC CYREG_PRT1_PC
#define led_red__0__PC2 CYREG_PRT1_PC2
#define led_red__0__PORT 1u
#define led_red__0__PS CYREG_PRT1_PS
#define led_red__0__SHIFT 6
#define led_red__DR CYREG_PRT1_DR
#define led_red__INTCFG CYREG_PRT1_INTCFG
#define led_red__INTSTAT CYREG_PRT1_INTSTAT
#define led_red__MASK 0x40u
#define led_red__PA__CFG0 CYREG_UDB_PA1_CFG0
#define led_red__PA__CFG1 CYREG_UDB_PA1_CFG1
#define led_red__PA__CFG10 CYREG_UDB_PA1_CFG10
#define led_red__PA__CFG11 CYREG_UDB_PA1_CFG11
#define led_red__PA__CFG12 CYREG_UDB_PA1_CFG12
#define led_red__PA__CFG13 CYREG_UDB_PA1_CFG13
#define led_red__PA__CFG14 CYREG_UDB_PA1_CFG14
#define led_red__PA__CFG2 CYREG_UDB_PA1_CFG2
#define led_red__PA__CFG3 CYREG_UDB_PA1_CFG3
#define led_red__PA__CFG4 CYREG_UDB_PA1_CFG4
#define led_red__PA__CFG5 CYREG_UDB_PA1_CFG5
#define led_red__PA__CFG6 CYREG_UDB_PA1_CFG6
#define led_red__PA__CFG7 CYREG_UDB_PA1_CFG7
#define led_red__PA__CFG8 CYREG_UDB_PA1_CFG8
#define led_red__PA__CFG9 CYREG_UDB_PA1_CFG9
#define led_red__PC CYREG_PRT1_PC
#define led_red__PC2 CYREG_PRT1_PC2
#define led_red__PORT 1u
#define led_red__PS CYREG_PRT1_PS
#define led_red__SHIFT 6

/* led_blue */
#define led_blue__0__DM__MASK 0xE00u
#define led_blue__0__DM__SHIFT 9
#define led_blue__0__DR CYREG_PRT0_DR
#define led_blue__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define led_blue__0__HSIOM_MASK 0x0000F000u
#define led_blue__0__HSIOM_SHIFT 12u
#define led_blue__0__INTCFG CYREG_PRT0_INTCFG
#define led_blue__0__INTSTAT CYREG_PRT0_INTSTAT
#define led_blue__0__MASK 0x08u
#define led_blue__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define led_blue__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define led_blue__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define led_blue__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define led_blue__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define led_blue__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define led_blue__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define led_blue__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define led_blue__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define led_blue__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define led_blue__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define led_blue__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define led_blue__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define led_blue__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define led_blue__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define led_blue__0__PC CYREG_PRT0_PC
#define led_blue__0__PC2 CYREG_PRT0_PC2
#define led_blue__0__PORT 0u
#define led_blue__0__PS CYREG_PRT0_PS
#define led_blue__0__SHIFT 3
#define led_blue__DR CYREG_PRT0_DR
#define led_blue__INTCFG CYREG_PRT0_INTCFG
#define led_blue__INTSTAT CYREG_PRT0_INTSTAT
#define led_blue__MASK 0x08u
#define led_blue__PA__CFG0 CYREG_UDB_PA0_CFG0
#define led_blue__PA__CFG1 CYREG_UDB_PA0_CFG1
#define led_blue__PA__CFG10 CYREG_UDB_PA0_CFG10
#define led_blue__PA__CFG11 CYREG_UDB_PA0_CFG11
#define led_blue__PA__CFG12 CYREG_UDB_PA0_CFG12
#define led_blue__PA__CFG13 CYREG_UDB_PA0_CFG13
#define led_blue__PA__CFG14 CYREG_UDB_PA0_CFG14
#define led_blue__PA__CFG2 CYREG_UDB_PA0_CFG2
#define led_blue__PA__CFG3 CYREG_UDB_PA0_CFG3
#define led_blue__PA__CFG4 CYREG_UDB_PA0_CFG4
#define led_blue__PA__CFG5 CYREG_UDB_PA0_CFG5
#define led_blue__PA__CFG6 CYREG_UDB_PA0_CFG6
#define led_blue__PA__CFG7 CYREG_UDB_PA0_CFG7
#define led_blue__PA__CFG8 CYREG_UDB_PA0_CFG8
#define led_blue__PA__CFG9 CYREG_UDB_PA0_CFG9
#define led_blue__PC CYREG_PRT0_PC
#define led_blue__PC2 CYREG_PRT0_PC2
#define led_blue__PORT 0u
#define led_blue__PS CYREG_PRT0_PS
#define led_blue__SHIFT 3

/* int_start */
#define int_start__INTC_CLR_EN_REG CYREG_CM0_ICER
#define int_start__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define int_start__INTC_MASK 0x01u
#define int_start__INTC_NUMBER 0u
#define int_start__INTC_PRIOR_MASK 0xC0u
#define int_start__INTC_PRIOR_NUM 3u
#define int_start__INTC_PRIOR_REG CYREG_CM0_IPR0
#define int_start__INTC_SET_EN_REG CYREG_CM0_ISER
#define int_start__INTC_SET_PD_REG CYREG_CM0_ISPR

/* int_cancel */
#define int_cancel__INTC_CLR_EN_REG CYREG_CM0_ICER
#define int_cancel__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define int_cancel__INTC_MASK 0x08u
#define int_cancel__INTC_NUMBER 3u
#define int_cancel__INTC_PRIOR_MASK 0xC0000000u
#define int_cancel__INTC_PRIOR_NUM 3u
#define int_cancel__INTC_PRIOR_REG CYREG_CM0_IPR0
#define int_cancel__INTC_SET_EN_REG CYREG_CM0_ISER
#define int_cancel__INTC_SET_PD_REG CYREG_CM0_ISPR

/* Miscellaneous */
#define CY_PROJECT_NAME "Design01"
#define CY_VERSION "PSoC Creator  3.3 SP1"
#define CYDEV_BCLK__HFCLK__HZ 24000000U
#define CYDEV_BCLK__HFCLK__KHZ 24000U
#define CYDEV_BCLK__HFCLK__MHZ 24U
#define CYDEV_BCLK__SYSCLK__HZ 24000000U
#define CYDEV_BCLK__SYSCLK__KHZ 24000U
#define CYDEV_BCLK__SYSCLK__MHZ 24U
#define CYDEV_CHIP_DIE_LEOPARD 1u
#define CYDEV_CHIP_DIE_PANTHER 18u
#define CYDEV_CHIP_DIE_PSOC4A 10u
#define CYDEV_CHIP_DIE_PSOC5LP 17u
#define CYDEV_CHIP_DIE_TMA4 2u
#define CYDEV_CHIP_DIE_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_PSOC3 1u
#define CYDEV_CHIP_FAMILY_PSOC4 2u
#define CYDEV_CHIP_FAMILY_PSOC5 3u
#define CYDEV_CHIP_FAMILY_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC4
#define CYDEV_CHIP_JTAG_ID 0x04C81193u
#define CYDEV_CHIP_MEMBER_3A 1u
#define CYDEV_CHIP_MEMBER_4A 10u
#define CYDEV_CHIP_MEMBER_4C 15u
#define CYDEV_CHIP_MEMBER_4D 6u
#define CYDEV_CHIP_MEMBER_4E 4u
#define CYDEV_CHIP_MEMBER_4F 11u
#define CYDEV_CHIP_MEMBER_4G 2u
#define CYDEV_CHIP_MEMBER_4H 9u
#define CYDEV_CHIP_MEMBER_4I 14u
#define CYDEV_CHIP_MEMBER_4J 7u
#define CYDEV_CHIP_MEMBER_4K 8u
#define CYDEV_CHIP_MEMBER_4L 13u
#define CYDEV_CHIP_MEMBER_4M 12u
#define CYDEV_CHIP_MEMBER_4N 5u
#define CYDEV_CHIP_MEMBER_4U 3u
#define CYDEV_CHIP_MEMBER_5A 17u
#define CYDEV_CHIP_MEMBER_5B 16u
#define CYDEV_CHIP_MEMBER_UNKNOWN 0u
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_4A
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_MEMBER_USED
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_REV_LEOPARD_ES1 0u
#define CYDEV_CHIP_REV_LEOPARD_ES2 1u
#define CYDEV_CHIP_REV_LEOPARD_ES3 3u
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3u
#define CYDEV_CHIP_REV_PANTHER_ES0 0u
#define CYDEV_CHIP_REV_PANTHER_ES1 1u
#define CYDEV_CHIP_REV_PANTHER_PRODUCTION 1u
#define CYDEV_CHIP_REV_PSOC4A_ES0 17u
#define CYDEV_CHIP_REV_PSOC4A_PRODUCTION 17u
#define CYDEV_CHIP_REV_PSOC5LP_ES0 0u
#define CYDEV_CHIP_REV_PSOC5LP_PRODUCTION 0u
#define CYDEV_CHIP_REV_TMA4_ES 17u
#define CYDEV_CHIP_REV_TMA4_ES2 33u
#define CYDEV_CHIP_REV_TMA4_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_3A_ES1 0u
#define CYDEV_CHIP_REVISION_3A_ES2 1u
#define CYDEV_CHIP_REVISION_3A_ES3 3u
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3u
#define CYDEV_CHIP_REVISION_4A_ES0 17u
#define CYDEV_CHIP_REVISION_4A_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4C_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4D_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4E_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256DMA 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256K 0u
#define CYDEV_CHIP_REVISION_4G_ES 17u
#define CYDEV_CHIP_REVISION_4G_ES2 33u
#define CYDEV_CHIP_REVISION_4G_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4H_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4I_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4J_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4K_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4L_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4M_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4N_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4U_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_5A_ES0 0u
#define CYDEV_CHIP_REVISION_5A_ES1 1u
#define CYDEV_CHIP_REVISION_5A_PRODUCTION 1u
#define CYDEV_CHIP_REVISION_5B_ES0 0u
#define CYDEV_CHIP_REVISION_5B_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_4A_PRODUCTION
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REVISION_USED
#define CYDEV_CONFIG_READ_ACCELERATOR 1
#define CYDEV_CONFIG_UNUSED_IO_AllowButWarn 0
#define CYDEV_CONFIG_UNUSED_IO CYDEV_CONFIG_UNUSED_IO_AllowButWarn
#define CYDEV_CONFIG_UNUSED_IO_AllowWithInfo 1
#define CYDEV_CONFIG_UNUSED_IO_Disallowed 2
#define CYDEV_CONFIGURATION_COMPRESSED 1
#define CYDEV_CONFIGURATION_MODE_COMPRESSED 0
#define CYDEV_CONFIGURATION_MODE CYDEV_CONFIGURATION_MODE_COMPRESSED
#define CYDEV_CONFIGURATION_MODE_DMA 2
#define CYDEV_CONFIGURATION_MODE_UNCOMPRESSED 1
#define CYDEV_DEBUG_PROTECT_KILL 4
#define CYDEV_DEBUG_PROTECT_OPEN 1
#define CYDEV_DEBUG_PROTECT CYDEV_DEBUG_PROTECT_OPEN
#define CYDEV_DEBUG_PROTECT_PROTECTED 2
#define CYDEV_DEBUGGING_DPS_Disable 3
#define CYDEV_DEBUGGING_DPS_SWD 2
#define CYDEV_DEBUGGING_DPS CYDEV_DEBUGGING_DPS_SWD
#define CYDEV_DEBUGGING_ENABLE 1
#define CYDEV_DFT_SELECT_CLK0 1u
#define CYDEV_DFT_SELECT_CLK1 2u
#define CYDEV_HEAP_SIZE 0x80
#define CYDEV_IMO_TRIMMED_BY_USB 0u
#define CYDEV_IMO_TRIMMED_BY_WCO 0u
#define CYDEV_IS_EXPORTING_CODE 0
#define CYDEV_IS_IMPORTING_CODE 0
#define CYDEV_PROJ_TYPE 0
#define CYDEV_PROJ_TYPE_BOOTLOADER 1
#define CYDEV_PROJ_TYPE_LAUNCHER 5
#define CYDEV_PROJ_TYPE_LOADABLE 2
#define CYDEV_PROJ_TYPE_LOADABLEANDBOOTLOADER 4
#define CYDEV_PROJ_TYPE_MULTIAPPBOOTLOADER 3
#define CYDEV_PROJ_TYPE_STANDARD 0
#define CYDEV_STACK_SIZE 0x0400
#define CYDEV_USE_BUNDLED_CMSIS 1
#define CYDEV_VARIABLE_VDDA 1
#define CYDEV_VDDA 3.3
#define CYDEV_VDDA_MV 3300
#define CYDEV_VDDD 3.3
#define CYDEV_VDDD_MV 3300
#define CYDEV_WDT_GENERATE_ISR 1u
#define CYIPBLOCK_M0S8_CTBM_VERSION 0
#define CYIPBLOCK_m0s8cpuss_VERSION 0
#define CYIPBLOCK_m0s8csd_VERSION 0
#define CYIPBLOCK_m0s8gpio2_VERSION 0
#define CYIPBLOCK_m0s8hsiom4a_VERSION 0
#define CYIPBLOCK_m0s8lcd_VERSION 0
#define CYIPBLOCK_m0s8lpcomp_VERSION 0
#define CYIPBLOCK_m0s8pclk_VERSION 0
#define CYIPBLOCK_m0s8sar_VERSION 0
#define CYIPBLOCK_m0s8scb_VERSION 0
#define CYIPBLOCK_m0s8srssv2_VERSION 1
#define CYIPBLOCK_m0s8tcpwm_VERSION 0
#define CYIPBLOCK_m0s8udbif_VERSION 0
#define CYIPBLOCK_S8_GPIO_VERSION 2
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
