/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "RTC.h"
#include "Timer_LED.h"
#include "UART_XB.h"
#include "UART_XB_SPI_UART.h"
#include "UART_XB_PINS.h"
#include "UART_XB_SPI_UART_PVT.h"
#include "UART_XB_PVT.h"
#include "UART_XB_BOOT.h"
#include "TimerTestMode.h"
#include "Clock_3.h"
#include "Int_timerTestMode.h"
#include "timer_clock.h"
#include "Int_Timer_Led.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "GatePin.h"
#include "GatePin_aliases.h"
#include "GATE_INT.h"
#include "LED_PIN.h"
#include "LED_PIN_aliases.h"
#include "debug.h"
#include "debug_aliases.h"
#include "debugntp.h"
#include "debugntp_aliases.h"
#include "ADC.h"
#include "voltage.h"
#include "voltage_aliases.h"
#include "Clock_1.h"
#include "DIN.h"
#include "DIN_aliases.h"
#include "CLK.h"
#include "CLK_aliases.h"
#include "CE.h"
#include "CE_aliases.h"
#include "RST.h"
#include "RST_aliases.h"
#include "DC.h"
#include "DC_aliases.h"
#include "MISO.h"
#include "MISO_aliases.h"
#include "LCD_BL.h"
#include "LCD_BL_aliases.h"
#include "AppDelay.h"
#include "timer_clock_2.h"
#include "Pin_testMode.h"
#include "Pin_testMode_aliases.h"
#include "SW_RunTestMode.h"
#include "SW_RunTestMode_aliases.h"
#include "UART_XB_SCBCLK.h"
#include "UART_XB_tx.h"
#include "UART_XB_tx_aliases.h"
#include "UART_XB_SCB_IRQ.h"
#include "UART_XB_rx.h"
#include "UART_XB_rx_aliases.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

