/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "timer_clock.h"
#include "Timer_LED.h"
#include "LCD_1.h"
#include "RTC_1.h"
#include "UART_PC.h"
#include "UART_PC_SPI_UART.h"
#include "UART_PC_PINS.h"
#include "UART_PC_SPI_UART_PVT.h"
#include "UART_PC_PVT.h"
#include "UART_PC_BOOT.h"
#include "Int_Timer_Led.h"
#include "LED_PIN.h"
#include "LED_PIN_aliases.h"
#include "Gate_Start.h"
#include "Gate_Start_aliases.h"
#include "WDT0_ISR.h"
#include "UART_XB.h"
#include "UART_XB_SPI_UART.h"
#include "UART_XB_PINS.h"
#include "UART_XB_SPI_UART_PVT.h"
#include "UART_XB_PVT.h"
#include "UART_XB_BOOT.h"
#include "LCD_1_LCDPort.h"
#include "LCD_1_LCDPort_aliases.h"
#include "UART_PC_SCBCLK.h"
#include "UART_PC_tx.h"
#include "UART_PC_tx_aliases.h"
#include "UART_PC_SCB_IRQ.h"
#include "UART_PC_rx.h"
#include "UART_PC_rx_aliases.h"
#include "UART_XB_SCBCLK.h"
#include "UART_XB_tx.h"
#include "UART_XB_tx_aliases.h"
#include "UART_XB_rx.h"
#include "UART_XB_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

