# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\Cypress\system-start-finish\vesion 2\fw\start\sandbox\test_rtc\Workspace01\test_rtc.cydsn\test_rtc.cyprj
# Date: Wed, 06 Jul 2016 14:39:56 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for D:\Cypress\system-start-finish\vesion 2\fw\start\sandbox\test_rtc\Workspace01\test_rtc.cydsn\TopDesign\TopDesign.cysch
# Project: D:\Cypress\system-start-finish\vesion 2\fw\start\sandbox\test_rtc\Workspace01\test_rtc.cydsn\test_rtc.cyprj
# Date: Wed, 06 Jul 2016 14:39:54 GMT
