/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_XB.h"
#include "UART_XB_SPI_UART.h"
#include "UART_XB_PINS.h"
#include "UART_XB_SPI_UART_PVT.h"
#include "UART_XB_PVT.h"
#include "UART_XB_BOOT.h"
#include "RTC.h"
#include "LCD.h"
#include "debug.h"
#include "debug_aliases.h"
#include "pinDebugNtp.h"
#include "pinDebugNtp_aliases.h"
#include "DEBUG_UART.h"
#include "DEBUG_UART_SPI_UART.h"
#include "DEBUG_UART_PINS.h"
#include "DEBUG_UART_SPI_UART_PVT.h"
#include "DEBUG_UART_PVT.h"
#include "DEBUG_UART_BOOT.h"
#include "UART_XB_SCBCLK.h"
#include "UART_XB_tx.h"
#include "UART_XB_tx_aliases.h"
#include "UART_XB_SCB_IRQ.h"
#include "UART_XB_rx.h"
#include "UART_XB_rx_aliases.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "DEBUG_UART_SCBCLK.h"
#include "DEBUG_UART_tx.h"
#include "DEBUG_UART_tx_aliases.h"
#include "DEBUG_UART_SCB_IRQ.h"
#include "DEBUG_UART_rx.h"
#include "DEBUG_UART_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

