# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\Cypress\system-start-finish\verison 1\fw\finish\sandbox\Workspace_finish_1\finish01.cydsn\finish01.cyprj
# Date: Sat, 02 Jul 2016 11:29:37 GMT
#set_units -time ns
create_clock -name {Clock(FFB)} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ff_div_8}]]
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {xbee_IntClock} -source [get_pins {ClockBlock/hfclk}] -edges {1 313 627} [list [get_pins {ClockBlock/udb_div_0}]]
create_generated_clock -name {Clock} -source [get_pins {ClockBlock/hfclk}] -edges {1 24001 48001} [list]


# Component constraints for D:\Cypress\system-start-finish\verison 1\fw\finish\sandbox\Workspace_finish_1\finish01.cydsn\TopDesign\TopDesign.cysch
# Project: D:\Cypress\system-start-finish\verison 1\fw\finish\sandbox\Workspace_finish_1\finish01.cydsn\finish01.cyprj
# Date: Sat, 02 Jul 2016 11:29:34 GMT
